spring.application.name: gateway-service

server:
  port: 8080

eureka:
  client:
    webclient:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
    jmx:
      exposure:
        exclude: '*'

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
      cache:
        enabled: false
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: micro-service
          uri: lb://micro-service-registry
          predicates:
            - Path=/services/**
          filters:
            - name: Retry
              args:
                retries: 3
                series: SERVER_ERROR
                backoff:
                  firstBackoff: 200ms
                  factor: 2

logging:
  level:
    com:
      netflix:
        debug
